#cloud-config
users:
 - name: dip
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHSzVnSooaSM04utwPJ5cI9I8UcbOM8elmXjFC9xMj+g
 - name: ansible
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICaUMW1hkguCZYFQWCKqH8aQNWhlW3X/XbEMKJnvpPjk

disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
dnf:
  preserve_sources_list: true

packages:
  - wget
  


runcmd:
 - [sh, -c, "wget -P /tmp/ https://github.com/vasev85/diplom/raw/master/elc/elasticsearch-8.6.1-x86_64.rpm"]
 - [sh, -c, "dnf -y install  /tmp/elasticsearch-8.6.1-x86_64.rpm"]
 - [sh, -c, "rm /etc/elasticsearch/elasticsearch.yml"]
 - [sh, -c, "wget -P /etc/elasticsearch/  https://github.com/vasev85/diplom/raw/master/elc/elasticsearch.yml"]
 
 
# - [sh, -c, "sudo wget -P /etc/systemd/system/ https://github.com/vasev85/diplom/raw/master/config/prometheus-nginxlog-exporter.service"]
# - [sh, -c, "wget -P /etc/ https://github.com/vasev85/diplom/raw/master/config/nginxlog_exporter.yml"]
# - [sh, -c, "wget -P /etc/systemd/system/ https://github.com/vasev85/diplom/raw/master/config/node_exporter.service"]
# - [sh, -c, "wget -P /tmp/ https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz"]
# - [sh, -c, "tar xvf /tmp/node_exporter-1.5.0.linux-amd64.tar.gz"]
# - [sh, -c, "cp -r /node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin"]
# - [sh, -c, "sudo useradd --no-create-home --shell /bin/false node_exporter"]
# - [sh, -c, "wget -P /tmp/  https://github.com/vasev85/diplom/raw/master/elc/filebeat-8.6.1-x86_64.rpm"]
# - [sh, -c, "sudo dnf -y install  /tmp/filebeat-8.6.1-x86_64.rpm"]
# - [sh, -c, "rm /etc/filebeat/filebeat.yml"]
# - [sh, -c, "wget -P /etc/filebeat https://github.com/vasev85/diplom/raw/master/elc/filebeat.yml"]
# 
# 
# 
#
# - [systemctl, enable, filebeat.service]
# - [systemctl, enable, nginx.service]
# - [systemctl, start, --no-block, nginx.service]
