#cloud-config
users:
 - name: dip
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHSzVnSooaSM04utwPJ5cI9I8UcbOM8elmXjFC9xMj+g
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
dnf:
  preserve_sources_list: true

packages:
  - grafana
  - wget
#provisioner: file 
# - source: /Users/mimac15-8/Desktop/terra/files/node_exporter.service
#   destination: /etc/systemd/system/node_exporter.service
#   - connection: 
#     type: ssh
#     user: dip
#     host_key: ~/.ssh/ya
  





runcmd:
#- [sh, -c, "wget -P /tmp/ https://github.com/vasev85/diplom/raw/master/grafana-enterprise-9.3.6-1.x86_64.rpm"]
#
#
# -  [sh,-c, "sudo dnf install y /tmp/grafana-enterprise-9.3.6-1.x86_64.rpm"]
# - [cp node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin]
# - [sudo useradd --no-create-home --shell /bin/false node_exporter]

 - [systemctl, enable, grafana-server.service]
 - [systemctl, start, --no-block, grafana-server.service]
 
 
 - [systemctl, grafana-server.service-reload ]
#  - [ systemctl, enable, nginx.service ]
#  - [ systemctl, start, --no-block, nginx.service ]
