#cloud-config
users:
 - name: dip
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHSzVnSooaSM04utwPJ5cI9I8UcbOM8elmXjFC9xMj+g
 - name: ansible
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICaUMW1hkguCZYFQWCKqH8aQNWhlW3X/XbEMKJnvpPjk

disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
dnf:
  preserve_sources_list: true

packages:
 - wget






runcmd:
 - [sh, -c, "wget -P /tmp/ https://github.com/vasev85/diplom/raw/master/elc/kibana-8.6.1-x86_64.rpm"]
 - [sh, -c, "dnf -y install  /tmp/kibana-8.6.1-x86_64.rpm"]
 - [sh, -c, "rm /etc/kibana/kibana.yml"]
 
 - [sh, -c, "wget -P /etc/kibana https://github.com/vasev85/diplom/raw/master/elc/kibana.yml"]
 
 
 

 - [systemctl, enable, kibana.service]
 - [systemctl, start, --no-block, kibana.service]
