#cloud-config
users:
 - name: dip
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHSzVnSooaSM04utwPJ5cI9I8UcbOM8elmXjFC9xMj+g
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
dnf:
  preserve_sources_list: true

packages:
  - nginx
  - wget
  -


runcmd:
 - [sh, -c, "wget -P /etc/systemd/system/ https://github.com/vasev85/diplom/raw/master/config/node_exporter.service"]
    https://github.com/vasev85/diplom/raw/master/config/node_exporter.service
 - [sh, -c, "wget -P /tmp/ https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz"]
 
 - [sh, -c, "tar xvf /tmp/node_exporter-1.5.0.linux-amd64.tar.gz"]
 - [sh, -c, "cp -r /node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin"]
 - [sh, -c, "sudo useradd --no-create-home --shell /bin/false node_exporter"]
 - [systemctl, enable, nginx.service]
 - [systemctl, start, --no-block, nginx.service]
 - [ sh, -c, "echo $(hostname | cut -d '.' -f 1 ) > /usr/share/nginx/html/index.html" ]
 - [ systemctl, nginx-reload]
 - [systemctl, start, --no-block, node_exporter.service]