#cloud-config
users:
 - name: dip
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHSzVnSooaSM04utwPJ5cI9I8UcbOM8elmXjFC9xMj+g
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
dnf:
  preserve_sources_list: true

packages:
  
 - wget



runcmd:
 - [sh, -c, "sudo useradd --no-create-home --shell /bin/false prometheus"]
 - [sh, -c, "wget -P /tmp/ https://github.com/prometheus/prometheus/releases/download/v2.41.0/prometheus-2.41.0.linux-amd64.tar.gz"]
 - [sh, -c, "tar xvf /tmp/prometheus-2.41.0.linux-amd64.tar.gz"]
 - [sh, -c, "sudo cp /prometheus-2.41.0.linux-amd64/prometheus /usr/local/bin"]
 - [sh, -c, "sudo cp /prometheus-2.41.0.linux-amd64/promtool /usr/local/bin"]
 - [sh, -c, "sudo mkdir /etc/prometheus"]
 - [sh, -c, "sudo mkdir /etc/alertmanager"]
 - [sh, -c, "sudo mkdir  /var/lib/prometheus"]
 - [sh, -c, "chmod -R 0774  /var/lib/prometheus"]
 - [sh, -c, "chown -R prometheus:prometheus  /var/lib/prometheus"]
 
 
 - [sh, -c, "sudo cp -r /prometheus-2.41.0.linux-amd64/consoles /etc/prometheus"]
 - [sh, -c, "sudo cp -r /prometheus-2.41.0.linux-amd64/console_libraries /etc/prometheus"]
 - [sh, -c, "sudo wget -P /etc/prometheus/ https://github.com/vasev85/diplom/raw/master/prometheus/prometheus.yml"]
 - [sh, -c, "sudo mkdir /etc/prometheus/sd_files/"]
 - [sh, -c, "sudo wget -P /etc/prometheus/sd_files/ https://github.com/vasev85/diplom/raw/master/prometheus/sd_files/nodeexporter.yml"] 

 
 - [sh, -c, "sudo wget -P /etc/systemd/system/ https://github.com/vasev85/diplom/raw/master/prometheus/prometheus.service"] 

 - [sh, -c, "wget -P /tmp/ https://github.com/prometheus/alertmanager/releases/download/v0.25.0/alertmanager-0.25.0.linux-amd64.tar.gz"]
 - [sh, -c, "tar xvf /tmp/alertmanager-0.25.0.linux-amd64.tar.gz"]
 - [sh, -c, "sudo cp /alertmanager-0.25.0.linux-amd64/alertmanager /usr/local/bin"]
 - [sh, -c, "sudo cp /alertmanager-0.25.0.linux-amd64/amtool /usr/local/bin"]
 - [sh, -c, "sudo wget -P /etc/alertmanager https://github.com/vasev85/diplom/raw/master/prometheus/alertmanager.yml"]  
 - [sh, -c, "sudo wget -P /etc/prometheus https://github.com/vasev85/diplom/raw/master/prometheus/alert.rules"]  
 - [sh, -c, "sudo wget -P /etc/systemd/system/ https://github.com/vasev85/diplom/raw/master/prometheus/alertmanager.service"]
 
 - [systemctl, start, --no-block, alertmanager.service]
 - [systemctl, start, --no-block, prometheus.service]

