---
- hosts: sg11
  
  
  tasks:

  - name: install sec-key
    copy: 
        src: "./ya" 
        dest: "/home/dip/.ssh/ya"
    - name: install pub-key
    copy: 
        src: "./ya.pub" 
        dest: "/home/dip/.ssh/ya.pub"
        
 # - name: Add user to remote hosts
#    user: name=ansible groups=wheel shell=/bin/bash append=yes password=$6$pPa0mSl/ONIk3M1R$d7gay.2em4zG2nO2IAdBBNCuKPbLiA7g.AcCD.i3WmhMQt1mv8yW4PcNKwNRmey2j1lEEdce1Q6OQfv6feoPc0
 - name: Создать 2048-битовый SSH ключ 
   user:
     name: ansible
     generate_ssh_key: yes
     ssh_key_bits: 2048
     ssh_key_file: .ssh/id_rsa-ya
     
     
 
  